/*
 * This file is generated by jOOQ.
 */
package com.adverity.challenge.adverity.database;


import com.adverity.challenge.adverity.database.tables.AggregateDfntn;
import com.adverity.challenge.adverity.database.tables.AggregateDfntnPkey;
import com.adverity.challenge.adverity.database.tables.CalendarDim;
import com.adverity.challenge.adverity.database.tables.CalendarDimPkey;
import com.adverity.challenge.adverity.database.tables.CampaignDim;
import com.adverity.challenge.adverity.database.tables.CampaignDimPkey;
import com.adverity.challenge.adverity.database.tables.DatasourceDim;
import com.adverity.challenge.adverity.database.tables.DatasourceDimPkey;
import com.adverity.challenge.adverity.database.tables.Ifact;
import com.adverity.challenge.adverity.database.tables.IfactAggregate;
import com.adverity.challenge.adverity.database.tables.IfactAggregatePkey;
import com.adverity.challenge.adverity.database.tables.IfactAggregateView;
import com.adverity.challenge.adverity.database.tables.IfactPkey;
import com.adverity.challenge.adverity.database.tables.MetricsDfntn;
import com.adverity.challenge.adverity.database.tables.MetricsDfntnPkey;
import com.adverity.challenge.adverity.database.tables.MetricsFact;
import com.adverity.challenge.adverity.database.tables.MetricsFactPkey;
import com.adverity.challenge.adverity.database.tables.SfactExt;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.aggregate_dfntn</code>.
     */
    public final AggregateDfntn AGGREGATE_DFNTN = AggregateDfntn.AGGREGATE_DFNTN;

    /**
     * The table <code>public.aggregate_dfntn_pkey</code>.
     */
    public final AggregateDfntnPkey AGGREGATE_DFNTN_PKEY = AggregateDfntnPkey.AGGREGATE_DFNTN_PKEY;

    /**
     * The table <code>public.calendar_dim</code>.
     */
    public final CalendarDim CALENDAR_DIM = CalendarDim.CALENDAR_DIM;

    /**
     * The table <code>public.calendar_dim_pkey</code>.
     */
    public final CalendarDimPkey CALENDAR_DIM_PKEY = CalendarDimPkey.CALENDAR_DIM_PKEY;

    /**
     * The table <code>public.campaign_dim</code>.
     */
    public final CampaignDim CAMPAIGN_DIM = CampaignDim.CAMPAIGN_DIM;

    /**
     * The table <code>public.campaign_dim_pkey</code>.
     */
    public final CampaignDimPkey CAMPAIGN_DIM_PKEY = CampaignDimPkey.CAMPAIGN_DIM_PKEY;

    /**
     * The table <code>public.datasource_dim</code>.
     */
    public final DatasourceDim DATASOURCE_DIM = DatasourceDim.DATASOURCE_DIM;

    /**
     * The table <code>public.datasource_dim_pkey</code>.
     */
    public final DatasourceDimPkey DATASOURCE_DIM_PKEY = DatasourceDimPkey.DATASOURCE_DIM_PKEY;

    /**
     * The table <code>public.ifact</code>.
     */
    public final Ifact IFACT = Ifact.IFACT;

    /**
     * The table <code>public.ifact_aggregate</code>.
     */
    public final IfactAggregate IFACT_AGGREGATE = IfactAggregate.IFACT_AGGREGATE;

    /**
     * The table <code>public.ifact_aggregate_pkey</code>.
     */
    public final IfactAggregatePkey IFACT_AGGREGATE_PKEY = IfactAggregatePkey.IFACT_AGGREGATE_PKEY;

    /**
     * The table <code>public.ifact_aggregate_view</code>.
     */
    public final IfactAggregateView IFACT_AGGREGATE_VIEW = IfactAggregateView.IFACT_AGGREGATE_VIEW;

    /**
     * The table <code>public.ifact_pkey</code>.
     */
    public final IfactPkey IFACT_PKEY = IfactPkey.IFACT_PKEY;

    /**
     * The table <code>public.metrics_dfntn</code>.
     */
    public final MetricsDfntn METRICS_DFNTN = MetricsDfntn.METRICS_DFNTN;

    /**
     * The table <code>public.metrics_dfntn_pkey</code>.
     */
    public final MetricsDfntnPkey METRICS_DFNTN_PKEY = MetricsDfntnPkey.METRICS_DFNTN_PKEY;

    /**
     * The table <code>public.metrics_fact</code>.
     */
    public final MetricsFact METRICS_FACT = MetricsFact.METRICS_FACT;

    /**
     * The table <code>public.metrics_fact_pkey</code>.
     */
    public final MetricsFactPkey METRICS_FACT_PKEY = MetricsFactPkey.METRICS_FACT_PKEY;

    /**
     * The table <code>public.sfact_ext</code>.
     */
    public final SfactExt SFACT_EXT = SfactExt.SFACT_EXT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            AggregateDfntn.AGGREGATE_DFNTN,
            AggregateDfntnPkey.AGGREGATE_DFNTN_PKEY,
            CalendarDim.CALENDAR_DIM,
            CalendarDimPkey.CALENDAR_DIM_PKEY,
            CampaignDim.CAMPAIGN_DIM,
            CampaignDimPkey.CAMPAIGN_DIM_PKEY,
            DatasourceDim.DATASOURCE_DIM,
            DatasourceDimPkey.DATASOURCE_DIM_PKEY,
            Ifact.IFACT,
            IfactAggregate.IFACT_AGGREGATE,
            IfactAggregatePkey.IFACT_AGGREGATE_PKEY,
            IfactAggregateView.IFACT_AGGREGATE_VIEW,
            IfactPkey.IFACT_PKEY,
            MetricsDfntn.METRICS_DFNTN,
            MetricsDfntnPkey.METRICS_DFNTN_PKEY,
            MetricsFact.METRICS_FACT,
            MetricsFactPkey.METRICS_FACT_PKEY,
            SfactExt.SFACT_EXT);
    }
}
