/*
 * This file is generated by jOOQ.
 */
package com.adverity.challenge.adverity.database;


import com.adverity.challenge.adverity.database.tables.AggregateDfntn;
import com.adverity.challenge.adverity.database.tables.AggregateDfntnPkey;
import com.adverity.challenge.adverity.database.tables.CalendarDim;
import com.adverity.challenge.adverity.database.tables.CalendarDimPkey;
import com.adverity.challenge.adverity.database.tables.CampaignDim;
import com.adverity.challenge.adverity.database.tables.CampaignDimPkey;
import com.adverity.challenge.adverity.database.tables.DatasourceDim;
import com.adverity.challenge.adverity.database.tables.DatasourceDimPkey;
import com.adverity.challenge.adverity.database.tables.Ifact;
import com.adverity.challenge.adverity.database.tables.IfactAggregate;
import com.adverity.challenge.adverity.database.tables.IfactAggregatePkey;
import com.adverity.challenge.adverity.database.tables.IfactAggregateView;
import com.adverity.challenge.adverity.database.tables.IfactPkey;
import com.adverity.challenge.adverity.database.tables.MetricsDfntn;
import com.adverity.challenge.adverity.database.tables.MetricsDfntnPkey;
import com.adverity.challenge.adverity.database.tables.MetricsFact;
import com.adverity.challenge.adverity.database.tables.MetricsFactPkey;
import com.adverity.challenge.adverity.database.tables.SfactExt;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.aggregate_dfntn</code>.
     */
    public static final AggregateDfntn AGGREGATE_DFNTN = AggregateDfntn.AGGREGATE_DFNTN;

    /**
     * The table <code>public.aggregate_dfntn_pkey</code>.
     */
    public static final AggregateDfntnPkey AGGREGATE_DFNTN_PKEY = AggregateDfntnPkey.AGGREGATE_DFNTN_PKEY;

    /**
     * The table <code>public.calendar_dim</code>.
     */
    public static final CalendarDim CALENDAR_DIM = CalendarDim.CALENDAR_DIM;

    /**
     * The table <code>public.calendar_dim_pkey</code>.
     */
    public static final CalendarDimPkey CALENDAR_DIM_PKEY = CalendarDimPkey.CALENDAR_DIM_PKEY;

    /**
     * The table <code>public.campaign_dim</code>.
     */
    public static final CampaignDim CAMPAIGN_DIM = CampaignDim.CAMPAIGN_DIM;

    /**
     * The table <code>public.campaign_dim_pkey</code>.
     */
    public static final CampaignDimPkey CAMPAIGN_DIM_PKEY = CampaignDimPkey.CAMPAIGN_DIM_PKEY;

    /**
     * The table <code>public.datasource_dim</code>.
     */
    public static final DatasourceDim DATASOURCE_DIM = DatasourceDim.DATASOURCE_DIM;

    /**
     * The table <code>public.datasource_dim_pkey</code>.
     */
    public static final DatasourceDimPkey DATASOURCE_DIM_PKEY = DatasourceDimPkey.DATASOURCE_DIM_PKEY;

    /**
     * The table <code>public.ifact</code>.
     */
    public static final Ifact IFACT = Ifact.IFACT;

    /**
     * The table <code>public.ifact_aggregate</code>.
     */
    public static final IfactAggregate IFACT_AGGREGATE = IfactAggregate.IFACT_AGGREGATE;

    /**
     * The table <code>public.ifact_aggregate_pkey</code>.
     */
    public static final IfactAggregatePkey IFACT_AGGREGATE_PKEY = IfactAggregatePkey.IFACT_AGGREGATE_PKEY;

    /**
     * The table <code>public.ifact_aggregate_view</code>.
     */
    public static final IfactAggregateView IFACT_AGGREGATE_VIEW = IfactAggregateView.IFACT_AGGREGATE_VIEW;

    /**
     * The table <code>public.ifact_pkey</code>.
     */
    public static final IfactPkey IFACT_PKEY = IfactPkey.IFACT_PKEY;

    /**
     * The table <code>public.metrics_dfntn</code>.
     */
    public static final MetricsDfntn METRICS_DFNTN = MetricsDfntn.METRICS_DFNTN;

    /**
     * The table <code>public.metrics_dfntn_pkey</code>.
     */
    public static final MetricsDfntnPkey METRICS_DFNTN_PKEY = MetricsDfntnPkey.METRICS_DFNTN_PKEY;

    /**
     * The table <code>public.metrics_fact</code>.
     */
    public static final MetricsFact METRICS_FACT = MetricsFact.METRICS_FACT;

    /**
     * The table <code>public.metrics_fact_pkey</code>.
     */
    public static final MetricsFactPkey METRICS_FACT_PKEY = MetricsFactPkey.METRICS_FACT_PKEY;

    /**
     * The table <code>public.sfact_ext</code>.
     */
    public static final SfactExt SFACT_EXT = SfactExt.SFACT_EXT;
}
