/*
 * This file is generated by jOOQ.
 */
package com.adverity.challenge.adverity.database.tables.records;


import com.adverity.challenge.adverity.database.tables.SfactExt;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SfactExtRecord extends TableRecordImpl<SfactExtRecord> implements Record5<String, String, String, Object, Object> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sfact_ext.datasource</code>.
     */
    public void setDatasource(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sfact_ext.datasource</code>.
     */
    public String getDatasource() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.sfact_ext.campaign</code>.
     */
    public void setCampaign(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sfact_ext.campaign</code>.
     */
    public String getCampaign() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.sfact_ext.daily</code>.
     */
    public void setDaily(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sfact_ext.daily</code>.
     */
    public String getDaily() {
        return (String) get(2);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public void setClicks(Object value) {
        set(3, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getClicks() {
        return get(3);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public void setImpressions(Object value) {
        set(4, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getImpressions() {
        return get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, Object, Object> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<String, String, String, Object, Object> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return SfactExt.SFACT_EXT.DATASOURCE;
    }

    @Override
    public Field<String> field2() {
        return SfactExt.SFACT_EXT.CAMPAIGN;
    }

    @Override
    public Field<String> field3() {
        return SfactExt.SFACT_EXT.DAILY;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field4() {
        return SfactExt.SFACT_EXT.CLICKS;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field5() {
        return SfactExt.SFACT_EXT.IMPRESSIONS;
    }

    @Override
    public String component1() {
        return getDatasource();
    }

    @Override
    public String component2() {
        return getCampaign();
    }

    @Override
    public String component3() {
        return getDaily();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object component4() {
        return getClicks();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object component5() {
        return getImpressions();
    }

    @Override
    public String value1() {
        return getDatasource();
    }

    @Override
    public String value2() {
        return getCampaign();
    }

    @Override
    public String value3() {
        return getDaily();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object value4() {
        return getClicks();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object value5() {
        return getImpressions();
    }

    @Override
    public SfactExtRecord value1(String value) {
        setDatasource(value);
        return this;
    }

    @Override
    public SfactExtRecord value2(String value) {
        setCampaign(value);
        return this;
    }

    @Override
    public SfactExtRecord value3(String value) {
        setDaily(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public SfactExtRecord value4(Object value) {
        setClicks(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public SfactExtRecord value5(Object value) {
        setImpressions(value);
        return this;
    }

    @Override
    public SfactExtRecord values(String value1, String value2, String value3, Object value4, Object value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SfactExtRecord
     */
    public SfactExtRecord() {
        super(SfactExt.SFACT_EXT);
    }

    /**
     * Create a detached, initialised SfactExtRecord
     */
    public SfactExtRecord(String datasource, String campaign, String daily, Object clicks, Object impressions) {
        super(SfactExt.SFACT_EXT);

        setDatasource(datasource);
        setCampaign(campaign);
        setDaily(daily);
        setClicks(clicks);
        setImpressions(impressions);
    }
}
