/*
 * This file is generated by jOOQ.
 */
package com.adverity.challenge.adverity.database.tables;


import com.adverity.challenge.adverity.database.Keys;
import com.adverity.challenge.adverity.database.Public;
import com.adverity.challenge.adverity.database.tables.records.AggregateDfntnRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AggregateDfntn extends TableImpl<AggregateDfntnRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.aggregate_dfntn</code>
     */
    public static final AggregateDfntn AGGREGATE_DFNTN = new AggregateDfntn();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AggregateDfntnRecord> getRecordType() {
        return AggregateDfntnRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<AggregateDfntnRecord, Object> ID = createField(DSL.name("id"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>public.aggregate_dfntn.description</code>.
     */
    public final TableField<AggregateDfntnRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(100), this, "");

    private AggregateDfntn(Name alias, Table<AggregateDfntnRecord> aliased) {
        this(alias, aliased, null);
    }

    private AggregateDfntn(Name alias, Table<AggregateDfntnRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.aggregate_dfntn</code> table reference
     */
    public AggregateDfntn(String alias) {
        this(DSL.name(alias), AGGREGATE_DFNTN);
    }

    /**
     * Create an aliased <code>public.aggregate_dfntn</code> table reference
     */
    public AggregateDfntn(Name alias) {
        this(alias, AGGREGATE_DFNTN);
    }

    /**
     * Create a <code>public.aggregate_dfntn</code> table reference
     */
    public AggregateDfntn() {
        this(DSL.name("aggregate_dfntn"), null);
    }

    public <O extends Record> AggregateDfntn(Table<O> child, ForeignKey<O, AggregateDfntnRecord> key) {
        super(child, key, AGGREGATE_DFNTN);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<AggregateDfntnRecord> getPrimaryKey() {
        return Keys.PK_AGGREGATE_DFNTN;
    }

    @Override
    public List<UniqueKey<AggregateDfntnRecord>> getKeys() {
        return Arrays.<UniqueKey<AggregateDfntnRecord>>asList(Keys.PK_AGGREGATE_DFNTN);
    }

    @Override
    public AggregateDfntn as(String alias) {
        return new AggregateDfntn(DSL.name(alias), this);
    }

    @Override
    public AggregateDfntn as(Name alias) {
        return new AggregateDfntn(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AggregateDfntn rename(String name) {
        return new AggregateDfntn(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AggregateDfntn rename(Name name) {
        return new AggregateDfntn(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Object, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
