/*
 * This file is generated by jOOQ.
 */
package com.adverity.challenge.adverity.database.tables;


import com.adverity.challenge.adverity.database.Public;
import com.adverity.challenge.adverity.database.tables.records.CalendarDimPkeyRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CalendarDimPkey extends TableImpl<CalendarDimPkeyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.calendar_dim_pkey</code>
     */
    public static final CalendarDimPkey CALENDAR_DIM_PKEY = new CalendarDimPkey();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CalendarDimPkeyRecord> getRecordType() {
        return CalendarDimPkeyRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<CalendarDimPkeyRecord, Object> ID = createField(DSL.name("id"), SQLDataType.OTHER, this, "");

    private CalendarDimPkey(Name alias, Table<CalendarDimPkeyRecord> aliased) {
        this(alias, aliased, null);
    }

    private CalendarDimPkey(Name alias, Table<CalendarDimPkeyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.calendar_dim_pkey</code> table reference
     */
    public CalendarDimPkey(String alias) {
        this(DSL.name(alias), CALENDAR_DIM_PKEY);
    }

    /**
     * Create an aliased <code>public.calendar_dim_pkey</code> table reference
     */
    public CalendarDimPkey(Name alias) {
        this(alias, CALENDAR_DIM_PKEY);
    }

    /**
     * Create a <code>public.calendar_dim_pkey</code> table reference
     */
    public CalendarDimPkey() {
        this(DSL.name("calendar_dim_pkey"), null);
    }

    public <O extends Record> CalendarDimPkey(Table<O> child, ForeignKey<O, CalendarDimPkeyRecord> key) {
        super(child, key, CALENDAR_DIM_PKEY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public CalendarDimPkey as(String alias) {
        return new CalendarDimPkey(DSL.name(alias), this);
    }

    @Override
    public CalendarDimPkey as(Name alias) {
        return new CalendarDimPkey(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CalendarDimPkey rename(String name) {
        return new CalendarDimPkey(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CalendarDimPkey rename(Name name) {
        return new CalendarDimPkey(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Object> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
