/*
 * This file is generated by jOOQ.
 */
package com.adverity.challenge.adverity.database.tables;


import com.adverity.challenge.adverity.database.Public;
import com.adverity.challenge.adverity.database.tables.records.CampaignDimPkeyRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CampaignDimPkey extends TableImpl<CampaignDimPkeyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.campaign_dim_pkey</code>
     */
    public static final CampaignDimPkey CAMPAIGN_DIM_PKEY = new CampaignDimPkey();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CampaignDimPkeyRecord> getRecordType() {
        return CampaignDimPkeyRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<CampaignDimPkeyRecord, Object> ID = createField(DSL.name("id"), SQLDataType.OTHER, this, "");

    private CampaignDimPkey(Name alias, Table<CampaignDimPkeyRecord> aliased) {
        this(alias, aliased, null);
    }

    private CampaignDimPkey(Name alias, Table<CampaignDimPkeyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.campaign_dim_pkey</code> table reference
     */
    public CampaignDimPkey(String alias) {
        this(DSL.name(alias), CAMPAIGN_DIM_PKEY);
    }

    /**
     * Create an aliased <code>public.campaign_dim_pkey</code> table reference
     */
    public CampaignDimPkey(Name alias) {
        this(alias, CAMPAIGN_DIM_PKEY);
    }

    /**
     * Create a <code>public.campaign_dim_pkey</code> table reference
     */
    public CampaignDimPkey() {
        this(DSL.name("campaign_dim_pkey"), null);
    }

    public <O extends Record> CampaignDimPkey(Table<O> child, ForeignKey<O, CampaignDimPkeyRecord> key) {
        super(child, key, CAMPAIGN_DIM_PKEY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public CampaignDimPkey as(String alias) {
        return new CampaignDimPkey(DSL.name(alias), this);
    }

    @Override
    public CampaignDimPkey as(Name alias) {
        return new CampaignDimPkey(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CampaignDimPkey rename(String name) {
        return new CampaignDimPkey(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CampaignDimPkey rename(Name name) {
        return new CampaignDimPkey(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Object> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
