/*
 * This file is generated by jOOQ.
 */
package com.adverity.challenge.adverity.database.tables;


import com.adverity.challenge.adverity.database.Keys;
import com.adverity.challenge.adverity.database.Public;
import com.adverity.challenge.adverity.database.tables.records.DatasourceDimRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DatasourceDim extends TableImpl<DatasourceDimRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.datasource_dim</code>
     */
    public static final DatasourceDim DATASOURCE_DIM = new DatasourceDim();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DatasourceDimRecord> getRecordType() {
        return DatasourceDimRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<DatasourceDimRecord, Object> ID = createField(DSL.name("id"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>public.datasource_dim.name</code>.
     */
    public final TableField<DatasourceDimRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    private DatasourceDim(Name alias, Table<DatasourceDimRecord> aliased) {
        this(alias, aliased, null);
    }

    private DatasourceDim(Name alias, Table<DatasourceDimRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.datasource_dim</code> table reference
     */
    public DatasourceDim(String alias) {
        this(DSL.name(alias), DATASOURCE_DIM);
    }

    /**
     * Create an aliased <code>public.datasource_dim</code> table reference
     */
    public DatasourceDim(Name alias) {
        this(alias, DATASOURCE_DIM);
    }

    /**
     * Create a <code>public.datasource_dim</code> table reference
     */
    public DatasourceDim() {
        this(DSL.name("datasource_dim"), null);
    }

    public <O extends Record> DatasourceDim(Table<O> child, ForeignKey<O, DatasourceDimRecord> key) {
        super(child, key, DATASOURCE_DIM);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<DatasourceDimRecord> getPrimaryKey() {
        return Keys.PK_DATASOURCE_DIM;
    }

    @Override
    public List<UniqueKey<DatasourceDimRecord>> getKeys() {
        return Arrays.<UniqueKey<DatasourceDimRecord>>asList(Keys.PK_DATASOURCE_DIM);
    }

    @Override
    public DatasourceDim as(String alias) {
        return new DatasourceDim(DSL.name(alias), this);
    }

    @Override
    public DatasourceDim as(Name alias) {
        return new DatasourceDim(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DatasourceDim rename(String name) {
        return new DatasourceDim(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DatasourceDim rename(Name name) {
        return new DatasourceDim(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Object, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
