/*
 * This file is generated by jOOQ.
 */
package com.adverity.challenge.adverity.database.tables;


import com.adverity.challenge.adverity.database.Keys;
import com.adverity.challenge.adverity.database.Public;
import com.adverity.challenge.adverity.database.tables.records.IfactRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ifact extends TableImpl<IfactRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ifact</code>
     */
    public static final Ifact IFACT = new Ifact();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IfactRecord> getRecordType() {
        return IfactRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<IfactRecord, Object> ID = createField(DSL.name("id"), SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<IfactRecord, Object> DATASOURCE_ID = createField(DSL.name("datasource_id"), SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<IfactRecord, Object> CAMPAIGN_ID = createField(DSL.name("campaign_id"), SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<IfactRecord, Object> CALENDAR_ID = createField(DSL.name("calendar_id"), SQLDataType.OTHER, this, "");

    private Ifact(Name alias, Table<IfactRecord> aliased) {
        this(alias, aliased, null);
    }

    private Ifact(Name alias, Table<IfactRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.ifact</code> table reference
     */
    public Ifact(String alias) {
        this(DSL.name(alias), IFACT);
    }

    /**
     * Create an aliased <code>public.ifact</code> table reference
     */
    public Ifact(Name alias) {
        this(alias, IFACT);
    }

    /**
     * Create a <code>public.ifact</code> table reference
     */
    public Ifact() {
        this(DSL.name("ifact"), null);
    }

    public <O extends Record> Ifact(Table<O> child, ForeignKey<O, IfactRecord> key) {
        super(child, key, IFACT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<IfactRecord> getPrimaryKey() {
        return Keys.PK_IFACT;
    }

    @Override
    public List<UniqueKey<IfactRecord>> getKeys() {
        return Arrays.<UniqueKey<IfactRecord>>asList(Keys.PK_IFACT);
    }

    @Override
    public Ifact as(String alias) {
        return new Ifact(DSL.name(alias), this);
    }

    @Override
    public Ifact as(Name alias) {
        return new Ifact(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Ifact rename(String name) {
        return new Ifact(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Ifact rename(Name name) {
        return new Ifact(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Object, Object, Object, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
