/*
 * This file is generated by jOOQ.
 */
package com.adverity.challenge.adverity.database.tables;


import com.adverity.challenge.adverity.database.Public;
import com.adverity.challenge.adverity.database.tables.records.IfactPkeyRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IfactPkey extends TableImpl<IfactPkeyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ifact_pkey</code>
     */
    public static final IfactPkey IFACT_PKEY = new IfactPkey();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IfactPkeyRecord> getRecordType() {
        return IfactPkeyRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<IfactPkeyRecord, Object> ID = createField(DSL.name("id"), SQLDataType.OTHER, this, "");

    private IfactPkey(Name alias, Table<IfactPkeyRecord> aliased) {
        this(alias, aliased, null);
    }

    private IfactPkey(Name alias, Table<IfactPkeyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.ifact_pkey</code> table reference
     */
    public IfactPkey(String alias) {
        this(DSL.name(alias), IFACT_PKEY);
    }

    /**
     * Create an aliased <code>public.ifact_pkey</code> table reference
     */
    public IfactPkey(Name alias) {
        this(alias, IFACT_PKEY);
    }

    /**
     * Create a <code>public.ifact_pkey</code> table reference
     */
    public IfactPkey() {
        this(DSL.name("ifact_pkey"), null);
    }

    public <O extends Record> IfactPkey(Table<O> child, ForeignKey<O, IfactPkeyRecord> key) {
        super(child, key, IFACT_PKEY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public IfactPkey as(String alias) {
        return new IfactPkey(DSL.name(alias), this);
    }

    @Override
    public IfactPkey as(Name alias) {
        return new IfactPkey(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public IfactPkey rename(String name) {
        return new IfactPkey(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IfactPkey rename(Name name) {
        return new IfactPkey(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Object> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
