/*
 * This file is generated by jOOQ.
 */
package com.adverity.challenge.adverity.database.tables;


import com.adverity.challenge.adverity.database.Public;
import com.adverity.challenge.adverity.database.tables.records.MetricsDfntnPkeyRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetricsDfntnPkey extends TableImpl<MetricsDfntnPkeyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.metrics_dfntn_pkey</code>
     */
    public static final MetricsDfntnPkey METRICS_DFNTN_PKEY = new MetricsDfntnPkey();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MetricsDfntnPkeyRecord> getRecordType() {
        return MetricsDfntnPkeyRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<MetricsDfntnPkeyRecord, Object> ID = createField(DSL.name("id"), SQLDataType.OTHER, this, "");

    private MetricsDfntnPkey(Name alias, Table<MetricsDfntnPkeyRecord> aliased) {
        this(alias, aliased, null);
    }

    private MetricsDfntnPkey(Name alias, Table<MetricsDfntnPkeyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.metrics_dfntn_pkey</code> table reference
     */
    public MetricsDfntnPkey(String alias) {
        this(DSL.name(alias), METRICS_DFNTN_PKEY);
    }

    /**
     * Create an aliased <code>public.metrics_dfntn_pkey</code> table reference
     */
    public MetricsDfntnPkey(Name alias) {
        this(alias, METRICS_DFNTN_PKEY);
    }

    /**
     * Create a <code>public.metrics_dfntn_pkey</code> table reference
     */
    public MetricsDfntnPkey() {
        this(DSL.name("metrics_dfntn_pkey"), null);
    }

    public <O extends Record> MetricsDfntnPkey(Table<O> child, ForeignKey<O, MetricsDfntnPkeyRecord> key) {
        super(child, key, METRICS_DFNTN_PKEY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public MetricsDfntnPkey as(String alias) {
        return new MetricsDfntnPkey(DSL.name(alias), this);
    }

    @Override
    public MetricsDfntnPkey as(Name alias) {
        return new MetricsDfntnPkey(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MetricsDfntnPkey rename(String name) {
        return new MetricsDfntnPkey(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MetricsDfntnPkey rename(Name name) {
        return new MetricsDfntnPkey(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Object> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
