/*
 * This file is generated by jOOQ.
 */
package com.adverity.challenge.adverity.database.tables;


import com.adverity.challenge.adverity.database.Public;
import com.adverity.challenge.adverity.database.tables.records.MetricsFactPkeyRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetricsFactPkey extends TableImpl<MetricsFactPkeyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.metrics_fact_pkey</code>
     */
    public static final MetricsFactPkey METRICS_FACT_PKEY = new MetricsFactPkey();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MetricsFactPkeyRecord> getRecordType() {
        return MetricsFactPkeyRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<MetricsFactPkeyRecord, Object> ID = createField(DSL.name("id"), SQLDataType.OTHER, this, "");

    private MetricsFactPkey(Name alias, Table<MetricsFactPkeyRecord> aliased) {
        this(alias, aliased, null);
    }

    private MetricsFactPkey(Name alias, Table<MetricsFactPkeyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.metrics_fact_pkey</code> table reference
     */
    public MetricsFactPkey(String alias) {
        this(DSL.name(alias), METRICS_FACT_PKEY);
    }

    /**
     * Create an aliased <code>public.metrics_fact_pkey</code> table reference
     */
    public MetricsFactPkey(Name alias) {
        this(alias, METRICS_FACT_PKEY);
    }

    /**
     * Create a <code>public.metrics_fact_pkey</code> table reference
     */
    public MetricsFactPkey() {
        this(DSL.name("metrics_fact_pkey"), null);
    }

    public <O extends Record> MetricsFactPkey(Table<O> child, ForeignKey<O, MetricsFactPkeyRecord> key) {
        super(child, key, METRICS_FACT_PKEY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public MetricsFactPkey as(String alias) {
        return new MetricsFactPkey(DSL.name(alias), this);
    }

    @Override
    public MetricsFactPkey as(Name alias) {
        return new MetricsFactPkey(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MetricsFactPkey rename(String name) {
        return new MetricsFactPkey(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MetricsFactPkey rename(Name name) {
        return new MetricsFactPkey(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Object> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
