/*
 * This file is generated by jOOQ.
 */
package com.adverity.challenge.adverity.database.tables;


import com.adverity.challenge.adverity.database.Keys;
import com.adverity.challenge.adverity.database.Public;
import com.adverity.challenge.adverity.database.tables.records.MetricsDfntnRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetricsDfntn extends TableImpl<MetricsDfntnRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.metrics_dfntn</code>
     */
    public static final MetricsDfntn METRICS_DFNTN = new MetricsDfntn();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MetricsDfntnRecord> getRecordType() {
        return MetricsDfntnRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<MetricsDfntnRecord, Object> ID = createField(DSL.name("id"), SQLDataType.OTHER, this, "");

    /**
     * The column <code>public.metrics_dfntn.name</code>.
     */
    public final TableField<MetricsDfntnRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.metrics_dfntn.description</code>.
     */
    public final TableField<MetricsDfntnRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "");

    private MetricsDfntn(Name alias, Table<MetricsDfntnRecord> aliased) {
        this(alias, aliased, null);
    }

    private MetricsDfntn(Name alias, Table<MetricsDfntnRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.metrics_dfntn</code> table reference
     */
    public MetricsDfntn(String alias) {
        this(DSL.name(alias), METRICS_DFNTN);
    }

    /**
     * Create an aliased <code>public.metrics_dfntn</code> table reference
     */
    public MetricsDfntn(Name alias) {
        this(alias, METRICS_DFNTN);
    }

    /**
     * Create a <code>public.metrics_dfntn</code> table reference
     */
    public MetricsDfntn() {
        this(DSL.name("metrics_dfntn"), null);
    }

    public <O extends Record> MetricsDfntn(Table<O> child, ForeignKey<O, MetricsDfntnRecord> key) {
        super(child, key, METRICS_DFNTN);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<MetricsDfntnRecord> getPrimaryKey() {
        return Keys.PK_METRICS_DFNTN;
    }

    @Override
    public List<UniqueKey<MetricsDfntnRecord>> getKeys() {
        return Arrays.<UniqueKey<MetricsDfntnRecord>>asList(Keys.PK_METRICS_DFNTN);
    }

    @Override
    public MetricsDfntn as(String alias) {
        return new MetricsDfntn(DSL.name(alias), this);
    }

    @Override
    public MetricsDfntn as(Name alias) {
        return new MetricsDfntn(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MetricsDfntn rename(String name) {
        return new MetricsDfntn(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MetricsDfntn rename(Name name) {
        return new MetricsDfntn(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Object, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
