/*
 * This file is generated by jOOQ.
 */
package com.adverity.challenge.adverity.database.tables;


import com.adverity.challenge.adverity.database.Public;
import com.adverity.challenge.adverity.database.tables.records.SfactExtRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SfactExt extends TableImpl<SfactExtRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sfact_ext</code>
     */
    public static final SfactExt SFACT_EXT = new SfactExt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SfactExtRecord> getRecordType() {
        return SfactExtRecord.class;
    }

    /**
     * The column <code>public.sfact_ext.datasource</code>.
     */
    public final TableField<SfactExtRecord, String> DATASOURCE = createField(DSL.name("datasource"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.sfact_ext.campaign</code>.
     */
    public final TableField<SfactExtRecord, String> CAMPAIGN = createField(DSL.name("campaign"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.sfact_ext.daily</code>.
     */
    public final TableField<SfactExtRecord, String> DAILY = createField(DSL.name("daily"), SQLDataType.VARCHAR(100), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<SfactExtRecord, Object> CLICKS = createField(DSL.name("clicks"), SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public final TableField<SfactExtRecord, Object> IMPRESSIONS = createField(DSL.name("impressions"), SQLDataType.OTHER, this, "");

    private SfactExt(Name alias, Table<SfactExtRecord> aliased) {
        this(alias, aliased, null);
    }

    private SfactExt(Name alias, Table<SfactExtRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.sfact_ext</code> table reference
     */
    public SfactExt(String alias) {
        this(DSL.name(alias), SFACT_EXT);
    }

    /**
     * Create an aliased <code>public.sfact_ext</code> table reference
     */
    public SfactExt(Name alias) {
        this(alias, SFACT_EXT);
    }

    /**
     * Create a <code>public.sfact_ext</code> table reference
     */
    public SfactExt() {
        this(DSL.name("sfact_ext"), null);
    }

    public <O extends Record> SfactExt(Table<O> child, ForeignKey<O, SfactExtRecord> key) {
        super(child, key, SFACT_EXT);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public SfactExt as(String alias) {
        return new SfactExt(DSL.name(alias), this);
    }

    @Override
    public SfactExt as(Name alias) {
        return new SfactExt(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SfactExt rename(String name) {
        return new SfactExt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SfactExt rename(Name name) {
        return new SfactExt(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<String, String, String, Object, Object> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
